name: Laravel

on: push

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: soved
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Set additional environment variables
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
        PERSONAL_WEBSITE_TOKEN: ${{ secrets.PERSONAL_WEBSITE_TOKEN }}
      run: |
        echo "DB_PORT=$DB_PORT" >> $GITHUB_ENV
        echo "GITHUB_TOKEN=$PERSONAL_WEBSITE_TOKEN" >> $GITHUB_ENV
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.test', '.env');"
    - name: Cache Dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache/files
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - name: Install Dependencies
      env:
        NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}
        NOVA_PASSWORD: ${{ secrets.NOVA_PASSWORD }}
      run: |
        composer config http-basic.nova.laravel.com "$NOVA_USERNAME" "$NOVA_PASSWORD"
        composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Run the database migrations
      run: php artisan migrate
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit --testdox
