name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: soved
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Set additional environment variables
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
        PERSONAL_WEBSITE_TOKEN: ${{ secrets.PERSONAL_WEBSITE_TOKEN }}
      run: |
        echo "::set-env name=DB_PORT::$DB_PORT"
        echo "::set-env name=GITHUB_TOKEN::$PERSONAL_WEBSITE_TOKEN"
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.test', '.env');"
    - name: Install Dependencies
      env:
        NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}
        NOVA_PASSWORD: ${{ secrets.NOVA_PASSWORD }}
      run: |
        composer config http-basic.nova.laravel.com "$NOVA_USERNAME" "$NOVA_PASSWORD"
        composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Run the database migrations
      run: php artisan migrate
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
